In [1]:
import pandas as pd
import numpy as np

In [2]:
properties_df = pd.read_csv('./data/properties_2016.csv')
train_df = pd.read_csv('./data/train_2016_v2.csv')

C:\Users\x003752\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (22,32,34,49,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
properties_df.parcelid.nunique()

2985217

In [7]:
train_df.parcelid.nunique()

90150

In [47]:
feat_df = pd.merge(train_df, properties_df, on='parcelid', how='left')
feat_df.head()

,parcelid,logerror,transactiondate,bathroomcnt_x,bedroomcnt_x,buildingqualitytypeid_x,calculatedbathnbr_x,calculatedfinishedsquarefeet_x,finishedsquarefeet12_x,fips_x,...,numberofstories,fireplaceflag,structuretaxvaluedollarcnt_y,taxvaluedollarcnt_y,assessmentyear_y,landtaxvaluedollarcnt_y,taxamount_y,taxdelinquencyflag,taxdelinquencyyear,censustractandblock_y
0,11016594,0.0276,2016-01-01,2.0,3.0,4.0,2.0,1684.0,1684.0,6037.0,...,NaN,NaN,122754.0,360170.0,2015.0,237416.0,6735.88,NaN,NaN,6.037107e+13
1,14366692,-0.1684,2016-01-01,3.5,4.0,NaN,3.5,2263.0,2263.0,6059.0,...,NaN,NaN,346458.0,585529.0,2015.0,239071.0,10153.02,NaN,NaN,NaN
2,12098116,-0.0040,2016-01-01,3.0,2.0,4.0,3.0,2217.0,2217.0,6037.0,...,NaN,NaN,61994.0,119906.0,2015.0,57912.0,11484.48,NaN,NaN,6.037464e+13
3,12643413,0.0218,2016-01-02,2.0,2.0,4.0,2.0,839.0,839.0,6037.0,...,NaN,NaN,171518.0,244880.0,2015.0,73362.0,3048.74,NaN,NaN,6.037296e+13
4,14432541,-0.0050,2016-01-02,2.5,4.0,NaN,2.5,2283.0,2283.0,6059.0,...,2.0,NaN,169574.0,434551.0,2015.0,264977.0,5488.96,NaN,NaN,6.059042e+13

In [48]:
pd.options.display.max_rows = 65

dtype_df = feat_df.dtypes.reset_index()
dtype_df.columns = ["Count", "Column Type"]
dtype_df

                             Count Column Type
0                         parcelid       int64
1                         logerror     float64
2                  transactiondate      object
3                    bathroomcnt_x     float64
4                     bedroomcnt_x     float64
5          buildingqualitytypeid_x     float64
6              calculatedbathnbr_x     float64
7   calculatedfinishedsquarefeet_x     float64
8           finishedsquarefeet12_x     float64
9                           fips_x     float64
10                   fullbathcnt_x     float64
11         heatingorsystemtypeid_x     float64
12                      latitude_x     float64
13                     longitude_x     float64
14             lotsizesquarefeet_x     float64
15     propertycountylandusecode_x      object
16         propertylandusetypeid_x     float64
17            propertyzoningdesc_x      object
18        rawcensustractandblock_x     float64
19                  regionidcity_x     float64
20                regionidcounty_x     float64
21                   regionidzip_x     float64
22                       roomcnt_x     float64
23                       unitcnt_x     float64
24                     yearbuilt_x     float64
25    structuretaxvaluedollarcnt_x     float64
26             taxvaluedollarcnt_x     float64
27                assessmentyear_x     float64
28         landtaxvaluedollarcnt_x     float64
29                     taxamount_x     float64
30           censustractandblock_x     float64
31           airconditioningtypeid     float64
..                             ...         ...
56             lotsizesquarefeet_y     float64
57                         poolcnt     float64
58                     poolsizesum     float64
59                    pooltypeid10     float64
60                     pooltypeid2     float64
61                     pooltypeid7     float64
62     propertycountylandusecode_y      object
63         propertylandusetypeid_y     float64
64            propertyzoningdesc_y      object
65        rawcensustractandblock_y     float64
66                  regionidcity_y     float64
67                regionidcounty_y     float64
68            regionidneighborhood     float64
69                   regionidzip_y     float64
70                       roomcnt_y     float64
71                     storytypeid     float64
72             threequarterbathnbr     float64
73          typeconstructiontypeid     float64
74                       unitcnt_y     float64
75              yardbuildingsqft17     float64
76              yardbuildingsqft26     float64
77                     yearbuilt_y     float64
78                 numberofstories     float64
79                   fireplaceflag      object
80    structuretaxvaluedollarcnt_y     float64
81             taxvaluedollarcnt_y     float64
82                assessmentyear_y     float64
83         landtaxvaluedollarcnt_y     float64
84                     taxamount_y     float64
85              taxdelinquencyflag      object
86              taxdelinquencyyear     float64
87           censustractandblock_y     float64

[88 rows x 2 columns]

In [49]:
missing_df = feat_df.isnull().sum(axis=0).reset_index()
missing_df.columns = ['column_name', 'missing_count']
missing_df['missing_ratio'] = missing_df['missing_count'] / feat_df.shape[0]
temp = missing_df.ix[missing_df['missing_ratio']>0.6]
temp

C:\Users\x003752\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

                 column_name  missing_count  missing_ratio
31     airconditioningtypeid          61494       0.681185
32  architecturalstyletypeid          90014       0.997109
33              basementsqft          90232       0.999524
36       buildingclasstypeid          90259       0.999823
39                decktypeid          89617       0.992711
40  finishedfloor1squarefeet          83419       0.924054
43      finishedsquarefeet13          90242       0.999634
44      finishedsquarefeet15          86711       0.960521
45      finishedsquarefeet50          83419       0.924054
46       finishedsquarefeet6          89854       0.995336
48              fireplacecnt          80668       0.893581
50              garagecarcnt          60338       0.668380
51           garagetotalsqft          60338       0.668380
52            hashottuborspa          87910       0.973802
57                   poolcnt          72374       0.801706
58               poolsizesum          89306       0.989266
59              pooltypeid10          89114       0.987139
60               pooltypeid2          89071       0.986663
61               pooltypeid7          73578       0.815043
68      regionidneighborhood          54263       0.601086
71               storytypeid          90232       0.999524
72       threequarterbathnbr          78266       0.866973
73    typeconstructiontypeid          89976       0.996688
75        yardbuildingsqft17          87629       0.970690
76        yardbuildingsqft26          90180       0.998948
78           numberofstories          69705       0.772141
79             fireplaceflag          90053       0.997541
85        taxdelinquencyflag          88492       0.980249
86        taxdelinquencyyear          88492       0.980249

In [56]:
missing_list = temp['column_name'].tolist()
extra = ['heatingorsystemtypeid','buildingqualitytypeid']
print (missing_list, extra)

['airconditioningtypeid', 'architecturalstyletypeid', 'basementsqft', 'buildingclasstypeid', 'decktypeid', 'finishedfloor1squarefeet', 'finishedsquarefeet13', 'finishedsquarefeet15', 'finishedsquarefeet50', 'finishedsquarefeet6', 'fireplacecnt', 'garagecarcnt', 'garagetotalsqft', 'hashottuborspa', 'poolcnt', 'poolsizesum', 'pooltypeid10', 'pooltypeid2', 'pooltypeid7', 'regionidneighborhood', 'storytypeid', 'threequarterbathnbr', 'typeconstructiontypeid', 'yardbuildingsqft17', 'yardbuildingsqft26', 'numberofstories', 'fireplaceflag', 'taxdelinquencyflag', 'taxdelinquencyyear'] ['heatingorsystemtypeid', 'buildingqualitytypeid']

In [58]:
set(missing_list)&set(extra)

set()

In [59]:
feat_df = feat_df.drop(missing_list, axis=1)

In [60]:
feat_df.head()

,parcelid,logerror,transactiondate,bathroomcnt_x,bedroomcnt_x,buildingqualitytypeid_x,calculatedbathnbr_x,calculatedfinishedsquarefeet_x,finishedsquarefeet12_x,fips_x,...,regionidzip_y,roomcnt_y,unitcnt_y,yearbuilt_y,structuretaxvaluedollarcnt_y,taxvaluedollarcnt_y,assessmentyear_y,landtaxvaluedollarcnt_y,taxamount_y,censustractandblock_y
0,11016594,0.0276,2016-01-01,2.0,3.0,4.0,2.0,1684.0,1684.0,6037.0,...,96370.0,0.0,1.0,1959.0,122754.0,360170.0,2015.0,237416.0,6735.88,6.037107e+13
1,14366692,-0.1684,2016-01-01,3.5,4.0,NaN,3.5,2263.0,2263.0,6059.0,...,96962.0,0.0,NaN,2014.0,346458.0,585529.0,2015.0,239071.0,10153.02,NaN
2,12098116,-0.0040,2016-01-01,3.0,2.0,4.0,3.0,2217.0,2217.0,6037.0,...,96293.0,0.0,1.0,1940.0,61994.0,119906.0,2015.0,57912.0,11484.48,6.037464e+13
3,12643413,0.0218,2016-01-02,2.0,2.0,4.0,2.0,839.0,839.0,6037.0,...,96222.0,0.0,1.0,1987.0,171518.0,244880.0,2015.0,73362.0,3048.74,6.037296e+13
4,14432541,-0.0050,2016-01-02,2.5,4.0,NaN,2.5,2283.0,2283.0,6059.0,...,96961.0,8.0,NaN,1981.0,169574.0,434551.0,2015.0,264977.0,5488.96,6.059042e+13

In [63]:
pd.get_dummies(feat_df, prefix = 'dum_',columns= ['buildingqualitytypeid_x'])

,parcelid,logerror,transactiondate,bathroomcnt_x,bedroomcnt_x,calculatedbathnbr_x,calculatedfinishedsquarefeet_x,finishedsquarefeet12_x,fips_x,fullbathcnt_x,...,taxamount_y,censustractandblock_y,dum__1.0,dum__4.0,dum__6.0,dum__7.0,dum__8.0,dum__10.0,dum__11.0,dum__12.0
0,11016594,0.0276,2016-01-01,2.0,3.0,2.0,1684.0,1684.0,6037.0,2.0,...,6735.88,6.037107e+13,0,1,0,0,0,0,0,0
1,14366692,-0.1684,2016-01-01,3.5,4.0,3.5,2263.0,2263.0,6059.0,3.0,...,10153.02,NaN,0,0,0,0,0,0,0,0
2,12098116,-0.0040,2016-01-01,3.0,2.0,3.0,2217.0,2217.0,6037.0,3.0,...,11484.48,6.037464e+13,0,1,0,0,0,0,0,0
3,12643413,0.0218,2016-01-02,2.0,2.0,2.0,839.0,839.0,6037.0,2.0,...,3048.74,6.037296e+13,0,1,0,0,0,0,0,0
4,14432541,-0.0050,2016-01-02,2.5,4.0,2.5,2283.0,2283.0,6059.0,2.0,...,5488.96,6.059042e+13,0,0,0,0,0,0,0,0
5,11509835,-0.2705,2016-01-02,4.0,4.0,4.0,3067.0,3067.0,6037.0,4.0,...,27126.57,6.037621e+13,1,0,0,0,0,0,0,0
6,12286022,0.0440,2016-01-02,1.0,2.0,1.0,1297.0,1297.0,6037.0,1.0,...,2304.97,6.037542e+13,0,0,0,1,0,0,0,0
7,17177301,0.1638,2016-01-02,2.5,3.0,2.5,1763.0,1763.0,6111.0,2.0,...,3745.50,6.111003e+13,0,0,0,0,0,0,0,0
8,14739064,-0.0030,2016-01-02,1.0,2.0,1.0,796.0,796.0,6059.0,1.0,...,2172.88,6.059042e+13,0,0,0,0,0,0,0,0
9,14677559,0.0843,2016-01-03,2.0,2.0,2.0,1260.0,1260.0,6059.0,2.0,...,1940.26,6.059063e+13,0,0,0,0,0,0,0,0
10,10854446,0.3825,2016-01-03,2.0,2.0,2.0,1417.0,1417.0,6037.0,2.0,...,1443.69,6.037141e+13,0,0,0,1,0,0,0,0
11,11672170,-0.0161,2016-01-03,4.0,5.0,4.0,3080.0,3080.0,6037.0,4.0,...,13428.94,6.037263e+13,1,0,0,0,0,0,0,0
12,10949761,0.0344,2016-01-03,2.0,3.0,2.0,1484.0,1484.0,6037.0,2.0,...,832.35,6.037311e+13,0,0,0,1,0,0,0,0
13,14665244,0.0816,2016-01-03,2.0,2.0,2.0,1249.0,1249.0,6059.0,2.0,...,6876.70,6.059063e+13,0,0,0,0,0,0,0,0
14,14148540,-0.0450,2016-01-03,2.0,2.0,2.0,1367.0,1367.0,6059.0,2.0,...,3192.28,6.059002e+13,0,0,0,0,0,0,0,0
15,14057104,0.0020,2016-01-03,2.0,3.0,2.0,1302.0,1302.0,6059.0,2.0,...,4036.32,6.059099e+13,0,0,0,0,0,0,0,0
16,17296797,0.0440,2016-01-03,2.5,3.0,2.5,1558.0,1558.0,6111.0,2.0,...,6383.74,6.111007e+13,0,0,0,0,0,0,0,0
17,12524288,-0.0419,2016-01-03,1.0,1.0,1.0,597.0,597.0,6037.0,1.0,...,913.17,6.037575e+13,0,0,0,1,0,0,0,0
18,14091502,-0.0020,2016-01-03,2.0,3.0,2.0,1321.0,1321.0,6059.0,2.0,...,3329.14,6.059100e+13,0,0,0,0,0,0,0,0
19,10815909,0.0100,2016-01-03,3.0,3.0,3.0,1727.0,1727.0,6037.0,3.0,...,5194.00,6.037140e+13,0,1,0,0,0,0,0,0
20,12453853,-0.0387,2016-01-03,1.0,2.0,1.0,840.0,840.0,6037.0,1.0,...,3211.31,6.037570e+13,0,0,0,1,0,0,0,0
21,14253461,0.0218,2016-01-03,2.0,2.0,2.0,1476.0,1476.0,6059.0,2.0,...,3090.72,6.059075e+13,0,0,0,0,0,0,0,0
22,14001034,0.0149,2016-01-03,2.0,4.0,2.0,1430.0,1430.0,6059.0,2.0,...,3020.24,6.059110e+13,0,0,0,0,0,0,0,0
23,11458863,0.1151,2016-01-03,4.0,3.0,4.0,3749.0,3749.0,6037.0,4.0,...,14747.98,6.037277e+13,0,1,0,0,0,0,0,0
24,13957980,-0.1696,2016-01-03,2.5,2.0,2.5,1213.0,1213.0,6059.0,2.0,...,4269.90,6.059089e+13,0,0,0,0,0,0,0,0
25,12752047,-0.0440,2016-01-03,4.0,3.0,4.0,1875.0,1875.0,6037.0,4.0,...,3249.37,6.037504e+13,0,0,0,1,0,0,0,0
26,11188425,-0.0747,2016-01-03,2.0,2.0,2.0,1302.0,1302.0,6037.0,2.0,...,3895.76,6.037910e+13,0,1,0,0,0,0,0,0
27,14646051,0.0080,2016-01-03,2.5,2.0,2.5,1858.0,1858.0,6059.0,2.0,...,9553.56,6.059042e+13,0,0,0,0,0,0,0,0
28,10805063,0.0010,2016-01-03,2.0,2.0,2.0,1045.0,1045.0,6037.0,2.0,...,3117.19,6.037140e+13,0,1,0,0,0,0,0,0
29,12524725,-0.0534,2016-01-03,3.0,2.0,3.0,1329.0,1329.0,6037.0,3.0,...,2648.96,6.037577e+13,0,1,0,0,0,0,0,0
30,11104966,-0.0398,2016-01-03,2.0,4.0,2.0,1144.0,1144.0,6037.0,2.0,...,4499.03,6.037920e+13,0,0,0,1,0,0,0,0
31,11624877,-0.0294,2016-01-03,2.0,2.0,2.0,1422.0,1422.0,6037.0,2.0,...,8048.18,6.037269e+13,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90243,17182881,-0.0111,2016-12-30,2.0,3.0,2.0,1381.0,1381.0,6111.0,2.0,...,1394.72,6.111005e+13,0,0,0,0,0,0,0,0
90244,11143993,-0.0294,2016-12-30,3.0,3.0,3.0,1635.0,1635.0,6037.0,3.0,...,5692.71,6.037920e+13,0,1,0,0,0,0,0,0
90245,10757551,0.0953,2016-12-30,3.0,3.0,3.0,2221.0,2221.0,6037.0,3.0,...,6427.03,6.037137e+13,0,1,0,0,0,0,0,0
90246,12558267,0.0139,2016-12-30,2.0,2.0,2.0,990.0,990.0,6037.0,2.0,...,6286.13,6.037576e+13,0,0,0,0,0,0,0,0
90247,11710734,0.2095,2016-12-30,2.0,2.0,2.0,1743.0,1743.0,6037.0,2.0,...,964.14,6.037234e+13,0,1,0,0,0,0,0,0
90248,14347592,0.0080,2016-12-30,2.5,4.0,2.5,2400.0,2400.0,6059.0,2.0,...,6379.72,6.059052e+13,0,0,0,0,0,0,0,0
90249,11341061,-0.1312,2016-12-30,1.0,1.0,1.0,480.0,480.0,6037.0,1.0,...,1295.30,6.037920e+13,0,0,0,1,0,0,0,0
90250,14027878,0.0421,2016-12-30,2.0,3.0,2.0,1649.0,1649.0,6059.0,2.0,...,3148.18,6.059100e+13,0,0,0,0,0,0,0,0
90251,12756771,0.0658,2016-12-30,1.0,3.0,1.0,1064.0,1064.0,6037.0,1.0,...,4038.70,6.037553e+13,0,0,0,1,0,0,0,0
90252,12758333,0.0030,2016-12-30,3.0,3.0,3.0,1528.0,1528.0,6037.0,3.0,...,2761.24,6.037553e+13,0,0,0,1,0,0,0,0
90253,11295458,-0.0294,2016-12-30,2.0,2.0,2.0,1056.0,1056.0,6037.0,2.0,...,1263.39,6.037901e+13,0,0,0,1,0,0,0,0
90254,12757889,-0.0111,2016-12-30,2.0,3.0,2.0,1188.0,1188.0,6037.0,2.0,...,4493.66,6.037553e+13,0,0,0,1,0,0,0,0
90255,11308315,0.0070,2016-12-30,3.0,5.0,3.0,3932.0,3932.0,6037.0,3.0,...,6461.79,6.037901e+13,0,1,0,0,0,0,0,0
90256,14353215,0.0218,2016-12-30,2.5,3.0,2.5,2109.0,2109.0,6059.0,2.0,...,7380.64,6.059052e+13,0,0,0,0,0,0,0,0
90257,10753416,0.0526,2016-12-30,2.0,2.0,2.0,1054.0,1054.0,6037.0,2.0,...,4330.78,6.037800e+13,0,1,0,0,0,0,0,0
90258,11756902,0.0889,2016-12-30,3.0,3.0,3.0,2535.0,2535.0,6037.0,3.0,...,6286.52,6.037213e+13,1,0,0,0,0,0,0,0
90259,11994047,0.0178,2016-12-30,2.0,1.0,2.0,1406.0,1406.0,6037.0,2.0,...,5459.11,6.037192e+13,1,0,0,0,0,0,0,0
90260,11440746,0.0237,2016-12-30,2.0,2.0,2.0,954.0,954.0,6037.0,2.0,...,3596.07,6.037604e+13,0,1,0,0,0,0,0,0
90261,11703478,0.0431,2016-12-30,1.0,3.0,1.0,1822.0,1822.0,6037.0,1.0,...,627.91,6.037232e+13,0,0,0,1,0,0,0,0
90262,10965821,-0.2231,2016-12-30,2.0,3.0,2.0,1456.0,1456.0,6037.0,2.0,...,3738.38,6.037107e+13,0,0,0,1,0,0,0,0
90263,12067066,0.1398,2016-12-30,2.0,2.0,2.0,1052.0,1052.0,6037.0,2.0,...,4044.68,6.037302e+13,0,0,0,1,0,0,0,0
90264,11683263,0.0478,2016-12-30,3.0,3.0,3.0,2712.0,2712.0,6037.0,3.0,...,18297.87,6.037801e+13,0,0,0,0,0,1,0,0
90265,12062080,-0.3769,2016-12-30,1.0,2.0,1.0,860.0,860.0,6037.0,1.0,...,3075.18,6.037302e+13,0,1,0,0,0,0,0,0
90266,12265636,-0.0030,2016-12-30,2.0,4.0,2.0,1496.0,NaN,6037.0,2.0,...,6137.29,6.037543e+13,0,0,0,1,0,0,0,0
90267,17109680,0.0010,2016-12-30,2.0,4.0,2.0,1830.0,1830.0,6111.0,2.0,...,3172.68,6.111002e+13,0,0,0,0,0,0,0,0
90268,12268527,-0.0151,2016-12-30,3.0,3.0,3.0,2438.0,2438.0,6037.0,3.0,...,5853.81,6.037541e+13,0,1,0,0,0,0,0,0
90269,12920746,0.0344,2016-12-30,2.0,3.0,2.0,1448.0,1448.0,6037.0,2.0,...,5311.03,6.037404e+13,0,1,0,0,0,0,0,0
90270,10774160,-0.0356,2016-12-30,1.0,1.0,1.0,653.0,653.0,6037.0,1.0,...,2495.24,6.037132e+13,0,1,0,0,0,0,0,0
90271,12046695,0.0070,2016-12-30,3.0,3.0,3.0,2856.0,2856.0,6037.0,3.0,...,1886.54,6.037301e+13,0,1,0,0,0,0,0,0
90272,12995401,-0.2679,2016-12-30,2.0,4.0,2.0,2617.0,NaN,6037.0,2.0,...,1925.70,6.037433e+13,0,0,0,1,0,0,0,0
90273,11402105,0.0602,2016-12-30,2.0,2.0,2.0,1034.0,1034.0,6037.0,2.0,...,2285.57,6.037601e+13,0,1,0,0,0,0,0,0
90274,12566293,0.4207,2016-12-30,1.0,3.0,1.0,1524.0,1524.0,6037.0,1.0,...,2560.96,6.037544e+13,0,0,0,1,0,0,0,0